### ISSUE TITLE
Unable to spin up the containers on Linux Mint

### ISSUE THREAD

**Issue by hanif-mianjee** [aschmelyun/docker-compose-laravel#129] opened 2021-11-21 17:54 UTC
Hi,

Has anyone faced the following issue? I am unable to spin the containers and with the root.

> creating libtool
appending configuration tag "CXX" to libtool
configure: patching config.h.in
configure: creating ./config.status
config.status: creating config.h
/bin/sh /usr/src/php/ext/pdo/libtool --mode=compile cc -I. -I/usr/src/php/ext/pdo -I/usr/src/php/ext/pdo/include -I/usr/src/php/ext/pdo/main -I/usr/src/php/ext/pdo -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib  -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DHAVE_CONFIG_H  -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64    -c /usr/src/php/ext/pdo/pdo.c -o pdo.lo 
make: /bin/sh: Operation not permitted
make: *** [Makefile:243: pdo.lo] Error 127
The command '/bin/sh -c docker-php-ext-install pdo pdo_mysql' returned a non-zero code: 2
ERROR: Service 'php' failed to build : Build failed

**Comment by nakarimi** [comment] 2022-04-04 07:24
the same issue, do you figure out how to solve this? @hanif-mianjee

**Comment by hanif-mianjee** [comment] 2022-04-04 10:17
> the same issue, do you figure out how to solve this? @hanif-mianjee

Nope :(

**Comment by aschmelyun** [comment] 2022-11-14 06:14
A few other people have referenced this issue from around this time. It should be resolved by now, but was originally caused by a bug in an Alpine Linux version. If you experience this, try setting a different version or base image OS in the `php.dockerfile` file.

**Closed by aschmelyun** 2022-11-14 06:14 UTC
