### ISSUE TITLE
The stream or file "/var/www/html/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied

### ISSUE THREAD

**Issue by joeariasc** [aschmelyun/docker-compose-laravel#49] opened 2020-06-27 21:14 UTC
I got the following error.
![Screenshot from 2020-06-27 16 09 45](https://user-images.githubusercontent.com/10789457/85932347-f72dd980-b890-11ea-89ca-ac51eb45e44b.png)

Currently I'm working on the Ubuntu 18.04 and created a laravel project with the version ^7.0.

On the console, the containers and the initial configuration ran well.
![Screenshot from 2020-06-27 16 14 30](https://user-images.githubusercontent.com/10789457/85932379-4d9b1800-b891-11ea-9684-4c788e3983ec.png)

**Comment by suhacb** [comment] 2020-06-28 11:46
I have the same issue. I am running Debian 10, my Laravel project source code in stored in a home subdirectory, owned by my user. I've already tried over 10 solutions proposed by various Stackoverflow posts and other sites, but the problem persists. I understand that the problem due to my local username, who owns the source directory, is different from php container's user, but I don't know how to fix it.

The funny thing is, when I ran migration in the artisan container, there were a few migration errors which were written successfully in Laravel's log file.

**Comment by vladutt** [comment] 2020-06-28 20:38
Try to give permissions to the storage folder.
`sudo chmod -R 777 storage` - local

Edit 2y later bcs i saw few emails on this:
Production: `sudo chmod -R a+rw storage`

after that run:
`php artisan cache:clear`
`php artisan config:clear`
`php artisan config:cache`

**Comment by suhacb** [comment] 2020-06-29 08:24
Dear @vladutt, thank you for responding quickly.

The above solution works. Exact steps are:
- `sudo chmod -R 777 storage`
- `docker-compose run --rm artisan cache:clear`
- `docker-compose run --rm artisan config:clear`
- `docker-compose run --rm artisan config:cache`

I am concerned about security of the proposed solution though. On local development environment, this is not a problem. But for public testing and production, when app is exposed publicly, should there be a different approach of setting up the storage directory permissions?

**Comment by AdrienPoupa** [comment] 2020-06-29 13:46
You should set the `user` in docker-compose.yml: https://medium.com/redbubble/running-a-docker-container-as-a-non-root-user-7d2e00f8ee15

Then, a chmod 755 will work

**Comment by Juan-de-Costa-Rica** [comment] 2020-07-03 04:00
After searching for hours and a lot of trial and error, I found a solution that doesn't require the dreaded `chmod 777` !

Adding `RUN apk add shadow && usermod -u 1000 www-data && groupmod -g 1000 www-data` to the Dockerfile seems to make all the permissions play nice. I'm not sure if there are undesired consequences to this, but working for me.

Found from: https://stackoverflow.com/questions/36824222/how-to-change-the-nginx-process-user-of-the-official-docker-image-nginx

**Comment by ecsuae** [comment] 2020-08-24 00:05
> After searching for hours and a lot of trial and error, I found a solution that doesn't require the dreaded `chmod 777` !
> 
> Adding `RUN apk add shadow && usermod -u 1000 www-data && groupmod -g 1000 www-data` to the Dockerfile seems to make all the permissions play nice. I'm not sure if there are undesired consequences to this, but working for me.
> 
> Found from: https://stackoverflow.com/questions/36824222/how-to-change-the-nginx-process-user-of-the-official-docker-image-nginx

do we need to set any permissions on /src folder  also? adding user in docker file only doesn't resolve the problem.

**Comment by suhacb** [comment] 2020-08-28 09:37
> > After searching for hours and a lot of trial and error, I found a solution that doesn't require the dreaded `chmod 777` !
> > Adding `RUN apk add shadow && usermod -u 1000 www-data && groupmod -g 1000 www-data` to the Dockerfile seems to make all the permissions play nice. I'm not sure if there are undesired consequences to this, but working for me.
> > Found from: https://stackoverflow.com/questions/36824222/how-to-change-the-nginx-process-user-of-the-official-docker-image-nginx
> 
> do we need to set any permissions on /src folder also? adding user in docker file only doesn't resolve the problem.

Just adding `RUN apk add shadow && usermod -u 1000 www-data && groupmod -g 1000 www-data` to the php container doesn't solve the issue. (note: the code is for alpine containers which I use)
Same goes for `RUN deluser www-data && adduser -DH -h /home/www-data -s /sbin/nologin -u 1000 www-data`, as suggested  in one of the comments here: https://stackoverflow.com/questions/36824222/how-to-change-the-nginx-process-user-of-the-official-docker-image-nginx
I wishfully tried running both commands, but the same problem occurs.

**Comment by suhacb** [comment] 2020-08-31 10:23
Update: it seems I've figured it out.

Running `RUN deluser www-data && adduser -DH -h /home/www-data -s /sbin/nologin -u 1000 www-data` in the PHP container is important, but it is not the full solution.

The problem is also cause by the composer container. The composer container initially creates the Laravel application, with all the directories and files. This image is, by default, run as root. As a consequence, all the directories and files created by composer are owned by root:root. The solution is to also run the composer image as user 1000. For now, I do it when I run docker-compose run on composer image.

`docker-compose run --rm --interactive --tty --user 1000:1000 composer create-project --prefer-dist laravel/laravel .`

If you already have a directory with Laravel application, the above solution won't work, as the directories and files are already created and owned by root:root. You need to delete the directory containing Laravel application and then re-install the application using the above docker-compose command.

I would also suggest a PR to improve the entire docker-compose setup in this repo.

**Comment by AdrienPoupa** [comment] 2020-08-31 11:50
> The solution is to also run the composer image as user 1000

Yeah this is precisely what I said here: https://github.com/aschmelyun/docker-compose-laravel/issues/49#issuecomment-651131620

You should do that for the artisan and app containers

**Comment by paranoiasystem** [comment] 2020-09-07 08:35
> > The solution is to also run the composer image as user 1000
> 
> Yeah this is precisely what I said here: [#49 (comment)](https://github.com/aschmelyun/docker-compose-laravel/issues/49#issuecomment-651131620)
> 
> For your existing files, you just need to run `chown -R 1000:1000 /yourproject && chmod -R 755 /yourproject` in your projects folder
> 
> You should do that for the artisan and app containers

I have cloned the project, startup the envirorment and I have create via composer container a new laravel app, but after I have the same issue I have applied this but i receive a 404 error, I have tried to launch a **_docker-compose run --rm artisan route:cache_** but this is the result:

```
Starting mysql ... done
Route cache cleared!

   LogicException 

  Unable to prepare route [api/user] for serialization. Uses Closure.

  at vendor/laravel/framework/src/Illuminate/Routing/Route.php:1150
    1146|      */
    1147|     public function prepareForSerialization()
    1148|     {
    1149|         if ($this->action['uses'] instanceof Closure) {
  > 1150|             throw new LogicException("Unable to prepare route [{$this->uri}] for serialization. Uses Closure.");
    1151|         }
    1152| 
    1153|         $this->compileRoute();
    1154| 

      +15 vendor frames 
  16  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

![image](https://user-images.githubusercontent.com/9149503/92366802-e5b94700-f0f5-11ea-9ed4-a36774a06fb3.png)

**Comment by AdrienPoupa** [comment] 2020-09-07 14:21
@paranoiasystem this is a different issue, unrelated to permission. It simply means that you need to remove any closure route before caching routes. The error message is self explanatory.

https://stackoverflow.com/a/45266424/11989865

**Comment by aschmelyun** [comment] 2021-08-20 03:39
Hey all! This issue is a bit old, but I wanted to give an update. Sorry it took me a while to get around to it.

I've pushed out a large update to this repo, specifically involving permissions. There's now a `.env.example` file, which contains two sets of user/group names. This file should be copied to `.env`, and modified to match the username and group of the `src` directory that stores your Laravel application's source files. Then, run `docker-compose build --no-cache` before spinning your container network up again.

**What the main permissions issue was:**

Since we're using mounted volumes, Docker was overwriting any permissions or `chown`s in the Dockerfiles, and instead was using the username and group from the host system. This was only occurring on Linux and Windows WSL-2 systems as far as I can tell, since MacOS uses a virtualization layer that masks that ownership. PHP was expecting a `www-user` user and group, likewise with Nginx.

**How it's solved now:**

The best way I figured around it is either dropping the volumes and using `ADD` in the dockerfiles to copy over the source code, modifying the permissions at build-time. The problem with this was that you lost the ability to work on your application and have your changes update in real-time.

Instead, during build-time I take the values from the `.env` file for username/group, and create them in the containers. By matching the user and group that exists on the host system with the same one in the container(s), the application doesn't encounter any read/write errors and can proceed smoothly. There was also a fix to allow php to run as root, even if it's not recommended, since some webservers have their single user set to root/root.

Let me know if you have any questions about this, or if it's still a problem after using the updated repo!

**Comment by yoanyahemdi** [comment] 2021-08-21 18:51
Hi @aschmelyun thank you for your recent last update on this!
When you say to copy the .env and modified to match username and group.
How do we get to know what are the username and group? For instance using the laravel/laravel default app you suggest from your video example: https://www.youtube.com/watch?v=5N6gTVCG_rw&list=RDCMUCc07-IBVwRlOsMg2WMdd8Sg&index=26

Thank you!

**Comment by RobertPlaiasu** [comment] 2021-08-25 13:39
I still have this problem after the update

**Comment by yoanyahemdi** [comment] 2021-08-25 13:48
It worked for me following the steps:

The username to be used, is the username of your linux/computer: username@repertory
Then you need to create a new .env directly where you found the .env-example file
Then I needed to replace "127.0.0.1" to "mysql" in the .env file of my application.

Thank you!

**Comment by RobertPlaiasu** [comment] 2021-08-25 14:03
> 
> 
> It worked for me following the steps:
> 
> The username to be used, is the username of your linux/computer: username@repertory
> Then you need to create a new .env directly where you found the .env-example file
> Then I needed to replace "127.0.0.1" to "mysql" in the .env file of my application.
> 
> Thank you!

Thank you ! Now it works for me .

**Comment by zaimazhar** [comment] 2021-10-31 15:42
Hi,

Went has been struggling with the same problem for the past few days too and I would like to share some possible solutions;

1. I installed both WSL2 (Ubuntu 20.04) and Docker images inside a drive where Windows is not installed using [move-wsl](https://github.com/pxlrbt/move-wsl). I do not know if this matters but try bringing back WSL2 to where your Windows installed but let Docker images stay in your other drive to save space. In my case still working fine until today.
2. Try both `sudo apt update` and `sudo apt-get update` on where you wanted to install your Laravel application. In my case, I installed it at `//wsl$/Ubuntu-20.04/home/<your-created-username-during-wsl2-installation>/<your-laravel-app>`
3. Adding `WWWGROUP=1000` and `WWWUSER=1000` in your `.env` file then `./vendor/bin/sail build --no-cache` to rebuild the images then `sudo ./vendor/bin/sail up -d`. I tried without `sudo` but Docker couldn't expose the port to my local machine.
4. Never start your Laravel application from the Docker Desktop dashboard, I started it once then I have to `sudo ./vendor/bin/sail stop` and rebuild them again.

I don't know which step solved the problem for me but this is what I did, in sequence. It might not be the ideal or conventional solution for everyone but it is worth a try.

**Comment by rizkytegar** [comment] 2022-10-31 09:26
> 

thanks

**Comment by murraygunn** [comment] 2022-11-01 19:26
I'm getting this same problem in Ubuntu 22.04. I've checked the .env and .env.example files, but neither have anything that looks like user/group names. What exactly do I need to add/change?

Here's my .env-example file.
```
APP_NAME=Laravel
APP_ENV=local
APP_KEY=
APP_DEBUG=true
APP_URL=http://localhost

LOG_CHANNEL=stack
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=example_app
DB_USERNAME=root
DB_PASSWORD=

BROADCAST_DRIVER=log
CACHE_DRIVER=file
FILESYSTEM_DISK=local
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

MEMCACHED_HOST=127.0.0.1

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=smtp
MAIL_HOST=mailhog
MAIL_PORT=1025
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS="hello@example.com"
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_HOST=
PUSHER_PORT=443
PUSHER_SCHEME=https
PUSHER_APP_CLUSTER=mt1

VITE_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
VITE_PUSHER_HOST="${PUSHER_HOST}"
VITE_PUSHER_PORT="${PUSHER_PORT}"
VITE_PUSHER_SCHEME="${PUSHER_SCHEME}"
VITE_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
```

**Comment by aschmelyun** [comment] 2022-11-14 05:34
> It worked for me following the steps:
> 
> The username to be used, is the username of your linux/computer: username@repertory Then you need to create a new .env directly where you found the .env-example file Then I needed to replace "127.0.0.1" to "mysql" in the .env file of my application.
> 
> Thank you!

Following this advice should work going forward. If you have any other issues that aren't fixed by this, the advice above, or what's in the README file under "Permissions Issues" please open up another ticket!

**Closed by aschmelyun** 2022-11-14 05:34 UTC

**Comment by enkracken** [comment] 2023-06-09 12:44
I use Ubuntu 22.04. The solution is:
SSH into Docker container:
`docker exec -it app_name-laravel.test-1 /bin/bash`
Change the owner of storage/framework and storage/logs to `sail` not `www-data`:
```
chown -R sail:sail storage/framework
chown -R sail:sail storage/logs
```
If it still don't work, try to install htop inside that docker container. Run htop. Find the user of `/var/www/artisan serve`. Then repeat the commands above but with that user, not `sail`. Good luck!

### Update
Or much better, create a group for root and user from docker (mine is sail):
`groupadd sailroot`
then add both root and sail to the group:
`usermod -a -G sailroot sail`
`usermod -a -G sailroot root`
Change group owner of storage logs and framework to the group:
`chown root:sailroot -R storage/framework`
Change file permission to 775 for both:
`chmod 775 -R storage/framework`
In this way, you can using `php artisan serve` using php installed locally, or with docker using sail. Remember to leave the user to root, and group sailroot (or whatever you named)

**Comment by ronald-kimeli** [comment] 2023-08-28 14:47
Use this technique for Ubuntu 22.04

You need to start your Laravel Sail container like this 

```bash 
docker exec -it app_name-laravel.test-1 /bin/bash
```
h1 Next create storage file by 

```bash 
mkdir /.storage
```
```bash
cd /storage
```
```bash 
mkdir -p framework/{sessions,views,cache}
```
Get back to root file or root container by 

```bash
cd ..
```

```bash
chmod -R ugo+rw /.storage || chmod 775 -R storage/
```
* This means storage file will be ready for new addition

Thank you Hope your problem solved!

**Comment by fernandomullerjr** [comment] 2024-06-22 04:32
Fixing Laravel log permission errors permanently:
https://devopsmind.com.br/en/troubleshooting-en/laravel-log-permission-errors/

**Comment by itxtoledo** [comment] 2025-01-14 15:15
> Fixing Laravel log permission errors permanently: https://devopsmind.com.br/en/troubleshooting-en/laravel-log-permission-errors/

broken url

**Comment by sheikhsalmanhossain** [comment] 2025-05-27 14:48
PERMISSION DENIED ISSUE.
HOW TO SOLVE THIS:

> docker exec -it (container-name) sh (access inside php container)

Fixing permission:
> chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache
>chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache

 (Base table not found issue):


> docker exec -it <php-container-name> php artisan session:table
> docker exec -it <php-container-name> php artisan migrate

NOW IT WORKS....

**Comment by 3bd-ulrahman** [comment] 2025-11-18 18:27
you need to install rootless mode in docker
check doc: https://docs.docker.com/engine/security/rootless
